apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temporal-java-shutdown
  name: temporal-java-shutdown
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-java-shutdown
  template:
    metadata:
      labels:
        app: temporal-java-shutdown
    spec:
      containers:
        - image: pvsone/temporal-java-shutdown:1.0.0
          imagePullPolicy: Always
          name: temporal-java-shutdown
          env:
            - name: SPRING_PROFILE
              value: tc
            - name: TEMPORAL_ADDRESS
              value: ${TEMPORAL_ADDRESS}
            - name: TEMPORAL_NAMESPACE
              value: ${TEMPORAL_NAMESPACE}
            - name: TEMPORAL_TLS_CERT
              value: /certs/tls.crt
            - name: TEMPORAL_TLS_KEY_PKCS8
              value: /certs/tls.key
          volumeMounts:
            - name: client-credential-volume
              mountPath: /certs
              readOnly: true
      volumes:
        - name: client-credential-volume
          secret:
            secretName: client-credential
