spring:
  application:
    name: temporal-java-shutdown
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workers:
      - name: shutdown-worker
        task-queue: shutdown-task-queue
    workersAutoDiscovery:
      packages:
        - com.example.workflows
        - com.example.activities

#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} {%X{WorkflowId} %X{ActivityId}} [%thread] %-5level %logger{36} - %msg %n"
#    console: "%d{HH:mm:ss.SSS} {%mdc} [%thread] %-5level %logger{36} - %msg %n"
